// <auto-generated />
namespace NewsBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class drop_old_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_old_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "202010052129184_drop_old_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
