// <auto-generated />
namespace NewsBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview2-19525-03")]
    public sealed partial class Create_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "202010052134587_Create_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
